databases:
  - name: alflix-db
    plan: free
    databaseName: alflix
    user: alflix

services:
  - type: web
    name: alflix
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "./start.sh"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.10
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "allflex-ota0.onrender.com,allflex.doccmed.uz,www.allflex.doccmed.uz,allflex.docmed.uz,www.allflex.docmed.uz"
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: "https://allflex-ota0.onrender.com,https://allflex.doccmed.uz,https://www.allflex.doccmed.uz,https://allflex.docmed.uz,https://www.allflex.docmed.uz"
      - key: DATABASE_URL
        fromDatabase:
          name: alflix-db
          property: connectionString
      - key: WEB_CONCURRENCY
        value: "2"
