# Generated by Django 6.0.6 on 2026-06-09 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0013_subscriptionplan_movie_created_at_movie_is_premium_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(choices=[('480', '480p'), ('720', '720p'), ('1080', '1080p'), ('4k', '4K')], max_length=10)),
                ('url', models.URLField(blank=True, default='')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_streams', to='movie.movie')),
            ],
            options={
                'ordering': ['quality'],
                'unique_together': {('movie', 'quality')},
            },
        ),
    ]
