# Generated by Django 6.0.6 on 2026-06-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0014_moviestream'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviestream',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='movies/videos/%Y/%m/'),
        ),
    ]
