# Generated by Django 6.0.6 on 2026-06-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0015_moviestream_video_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='live_posters/%Y/%m')),
                ('stream_url', models.URLField(blank=True, default='', verbose_name='Jonli efir URL')),
                ('is_live', models.BooleanField(default=False, verbose_name='Hozir efirda')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Live Stream',
                'verbose_name_plural': 'Live Streams',
                'ordering': ['-is_live', '-created_at'],
            },
        ),
    ]
