# Generated by Django 6.0.6 on 2026-06-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0020_category_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['order', 'price'], 'verbose_name': 'Subscription Plan', 'verbose_name_plural': 'Subscription Plans'},
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='access_live',
            field=models.BooleanField(default=True, verbose_name='Jonli efir'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='access_movies',
            field=models.BooleanField(default=True, verbose_name='Kinolar'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
