# Generated by Django 6.0.6 on 2026-06-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0021_plan_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_merchant_id', models.CharField(blank=True, default='', max_length=64)),
                ('click_service_id', models.CharField(blank=True, default='', max_length=64)),
                ('click_secret_key', models.CharField(blank=True, default='', max_length=128)),
                ('payme_merchant_id', models.CharField(blank=True, default='', max_length=64)),
                ('payme_secret_key', models.CharField(blank=True, default='', max_length=128)),
                ('test_mode_enabled', models.BooleanField(default=True, verbose_name='Sinov rejimi (DEBUG)')),
            ],
            options={
                'verbose_name': "To'lov sozlamalari",
            },
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='provider',
            field=models.CharField(choices=[('click', 'Click'), ('payme', 'Payme'), ('test', 'Test')], max_length=10),
        ),
    ]
