# Generated by Django 6.0.6 on 2026-06-10 08:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0022_payment_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['-is_corporate', 'order', 'price'], 'verbose_name': 'Subscription Plan', 'verbose_name_plural': 'Subscription Plans'},
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_corporate',
            field=models.BooleanField(default=False, verbose_name='Korporativ tarif'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_seats',
            field=models.PositiveIntegerField(default=10, help_text='Korporativ tarif uchun maksimal foydalanuvchilar soni', verbose_name='Xodimlar soni (korporativ)'),
        ),
        migrations.CreateModel(
            name='CorporateOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(blank=True, default='', max_length=150)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=30)),
                ('max_seats', models.PositiveIntegerField(default=10)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_corporate_orgs', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(limit_choices_to={'is_corporate': True}, on_delete=django.db.models.deletion.PROTECT, related_name='corporate_orgs', to='movie.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Korporativ tashkilot',
                'verbose_name_plural': 'Korporativ tashkilotlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CorporateSubscriptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('seats_requested', models.PositiveIntegerField(default=10)),
                ('message', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(limit_choices_to={'is_corporate': True}, on_delete=django.db.models.deletion.PROTECT, related_name='corporate_requests', to='movie.subscriptionplan')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corporate_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Korporativ so'rov",
                'verbose_name_plural': "Korporativ so'rovlar",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CorporateMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corporate_memberships', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='movie.corporateorganization')),
            ],
            options={
                'verbose_name': "Korporativ a'zo",
                'verbose_name_plural': "Korporativ a'zolar",
                'unique_together': {('organization', 'user')},
            },
        ),
    ]
