# Generated by Django 4.2.30 on 2026-06-10 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0023_corporate_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_uz', models.CharField(blank=True, default='', max_length=100)),
                ('name_en', models.CharField(blank=True, default='', max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(default='🎫', max_length=8)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Bilet bo'limi",
                'verbose_name_plural': "Bilet bo'limlari",
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='order_type',
            field=models.CharField(choices=[('subscription', 'Subscription'), ('ticket', 'Ticket')], default='subscription', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='ticket_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='movie.subscriptionplan'),
        ),
        migrations.CreateModel(
            name='TicketEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('venue', models.CharField(max_length=200)),
                ('city', models.CharField(default='Toshkent', max_length=100)),
                ('event_date', models.DateTimeField()),
                ('poster', models.ImageField(blank=True, null=True, upload_to='ticket_posters/%Y/%m')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_total', models.PositiveIntegerField(default=100)),
                ('quantity_sold', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='movie.ticketcategory')),
            ],
            options={
                'verbose_name': 'Tadbir',
                'verbose_name_plural': 'Tadbirlar',
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchasedTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_code', models.CharField(max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sold_tickets', to='movie.ticketevent')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_tickets', to='movie.paymentorder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sotilgan bilet',
                'verbose_name_plural': 'Sotilgan biletlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='ticket_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='movie.ticketevent'),
        ),
    ]
