# Generated by Django 4.2.30 on 2026-06-10 14:49

import uuid

from django.db import migrations, models
import django.db.models.deletion


def populate_referral_codes(apps, schema_editor):
    CorporateMember = apps.get_model('movie', 'CorporateMember')
    used = set(
        CorporateMember.objects.exclude(referral_code='').values_list('referral_code', flat=True)
    )
    for member in CorporateMember.objects.filter(referral_code=''):
        for _ in range(20):
            code = uuid.uuid4().hex[:12]
            if code not in used:
                member.referral_code = code
                used.add(code)
                member.save(update_fields=['referral_code'])
                break


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0024_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporatemember',
            name='referral_code',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
        migrations.AddField(
            model_name='corporatemember',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='movie.corporatemember'),
        ),
        migrations.RunPython(populate_referral_codes, migrations.RunPython.noop),
    ]
