# Generated by Django 4.2.30 on 2026-06-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0025_corporate_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketevent',
            name='age_limit',
            field=models.CharField(blank=True, default='6+', max_length=20),
        ),
        migrations.AddField(
            model_name='ticketevent',
            name='is_premiere',
            field=models.BooleanField(default=True, verbose_name='Premyera'),
        ),
        migrations.AddField(
            model_name='ticketevent',
            name='language',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='ticketevent',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='ticketevent',
            name='venue_address',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
