# Generated by Django 4.2.30 on 2026-06-10 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def populate_movie_protection(apps, schema_editor):
    Movie = apps.get_model('movie', 'Movie')
    used = set()
    for movie in Movie.objects.all():
        if not movie.movie_uid:
            for _ in range(30):
                import uuid
                code = f'AFLX-{uuid.uuid4().hex[:8].upper()}'
                if code not in used:
                    movie.movie_uid = code
                    used.add(code)
                    break
        if not movie.watermark_token:
            import uuid
            movie.watermark_token = f'WM-{uuid.uuid4().hex[:12].upper()}'
        if not movie.digital_passport_code:
            import hashlib
            raw = f'{movie.movie_uid}|{movie.title}|{movie.watermark_token}'
            digest = hashlib.sha256(raw.encode()).hexdigest()[:16].upper()
            movie.digital_passport_code = f'DP-{movie.movie_uid}-{digest}'
            movie.digital_passport = (
                f'{{"uid":"{movie.movie_uid}","hash":"{digest}","issuer":"AL-FLIX"}}'
            )
        movie.save()


def populate_user_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('movie', 'UserProfile')
    import secrets
    import string
    chars = string.ascii_uppercase + string.digits
    used = set(
        UserProfile.objects.exclude(subscriber_code='').values_list('subscriber_code', flat=True)
    )
    for user in User.objects.all():
        profile, created = UserProfile.objects.get_or_create(user=user)
        if not profile.subscriber_code:
            for _ in range(30):
                code = ''.join(secrets.choice(chars) for _ in range(10))
                if code not in used:
                    profile.subscriber_code = code
                    used.add(code)
                    profile.save(update_fields=['subscriber_code'])
                    break


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0026_ticket_premiere_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('partner_type', models.CharField(choices=[('telegram', 'Telegram kanal'), ('site', 'Sayt'), ('platform', 'Platforma')], default='site', max_length=20)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('website', models.URLField(blank=True, default='')),
                ('api_key', models.CharField(blank=True, max_length=64, unique=True)),
                ('revenue_share_percent', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('total_requests', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'API hamkor',
                'verbose_name_plural': 'API hamkorlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='digital_passport',
            field=models.TextField(blank=True, default='', verbose_name='Raqamli pasport (JSON)'),
        ),
        migrations.AddField(
            model_name='movie',
            name='digital_passport_code',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Pasport kodi'),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_uid',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Yagona ID'),
        ),
        migrations.AddField(
            model_name='movie',
            name='watermark_token',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Yashirin watermark'),
        ),
        migrations.RunPython(populate_movie_protection, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='movie',
            name='movie_uid',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Yagona ID'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_code', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi profili',
                'verbose_name_plural': 'Foydalanuvchi profillari',
            },
        ),
        migrations.RunPython(populate_user_profiles, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='userprofile',
            name='subscriber_code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='PiracyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_url', models.URLField(blank=True, default='')),
                ('detected_domain', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('reviewed', "Ko'rib chiqilgan"), ('resolved', 'Hal qilingan')], default='new', max_length=20)),
                ('notified_rights_holder', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piracy_alerts', to='movie.movie')),
            ],
            options={
                'verbose_name': 'Piratlik ogohlantirishi',
                'verbose_name_plural': 'Piratlik ogohlantirishlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('is_authorized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='movie.apipartner')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
