# Generated by Django 4.2.30 on 2026-06-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0028_nest_series_under_films'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_uid',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Yagona ID'),
        ),
    ]
