# Generated by Django 4.2.30 on 2026-06-18 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0031_telegram_storage'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='watchhistory',
            new_name='movie_watch_watched_89231c_idx',
            old_name='movie_watch_watched_6f0a0d_idx',
        ),
        migrations.RenameIndex(
            model_name='watchhistory',
            new_name='movie_watch_user_id_9938d2_idx',
            old_name='movie_watch_user_id_8c2f1a_idx',
        ),
    ]
